export const CZECH_DISCGOLF_COURSES = [
  "DGP Praha - Ladronka",
  "DGP Praha - Chodov",
  "DGP Praha - Krejcárek",
  "DGP Konopiště - Zámecký park",
  "DGP Konopiště - Spa",
  "DGP Brno - Milénova",
  "DGP Brno - Lesná",
  "DGP Ostrava - Jih",
  "DGP Hostačov",
  "DGP Moravský Krumlov",
  "DGP Kobylí",
  "DGP Budišov nad Budišovkou",
  "DGP Cheb - Myslivna",
  "DGP Kadaň",
  "DGP Kladno",
  "DGP Kolín",
  "DGP Kopřivnice",
  "DGP Krnov",
  "DGP Liberec - Vesec",
  "DGP Nový Jičín - Bocheta",
  "DGP Plzeň - Černice",
  "DGP Stříbro",
  "DGP Uničov",
  "DGP Valašské Meziříčí",
  "DGP Veselí nad Lužnicí",
  "DGP Vlašim",
  "DGP Zlín",
  "DGP České Budějovice - Stromovka",
  "DGP Humpolec",
  "DGP Jindřichův Hradec",
  "DGP Karviná",
  "DGP Kutná Hora",
  "DGP Olomouc - Pevnůstka",
  "DGP Písek",
  "DGP Prachatice",
  "DGP Svitavy",
  "DGP Třebíč",
  "DGP Ústí nad Labem - Severní Terasa",
  "DGP Velké Meziříčí",
  "DGP Žďár nad Sázavou"
].sort((a, b) => a.localeCompare(b, 'cs'));